version: '3'

services:
  web:
    build: .
    command: bash -c "cd parking_manager && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata parking_app/fixtures/*.json && python manage.py runserver 0.0.0.0:8000"
    container_name: parking_manager
    volumes:
      - .:/parking_manager
    ports:
      - "8000:8000"